#!/usr/bin/env node
/**
 * Reliability runner + logger.
 *
 * Runs the reliability lane and KEEPS A LOG of every run — pass or fail —
 * so the team can watch memory-system reliability over time:
 *   - test/reliability/runs.jsonl       one structured record per run (machine)
 *   - test/reliability/RELIABILITY-LOG.md  a human-readable table (last 30 runs)
 *
 * It captures the vitest JSON result + the scorecard metrics into one record,
 * then exits with vitest's own code so the CI gate still fails on regression.
 */

import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync, appendFileSync, mkdirSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '../..');
const JSON_OUT = resolve(HERE, '.last-run.json');
const RUNS_LOG = resolve(HERE, 'runs.jsonl');
const MD_LOG = resolve(HERE, 'RELIABILITY-LOG.md');
const SCORECARD = resolve(HERE, 'scorecard.json');

mkdirSync(HERE, { recursive: true });

// Run vitest: default reporter to the console (live progress) + json to a file.
const started = Date.now();
const res = spawnSync(
  'npx',
  [
    'vitest', 'run',
    '--config', 'vitest.reliability.config.js',
    '--reporter=default',
    '--reporter=json',
    `--outputFile.json=${JSON_OUT}`,
  ],
  { cwd: ROOT, stdio: 'inherit', env: process.env },
);
const durationMs = Date.now() - started;
const exitCode = res.status == null ? 1 : res.status;

// Parse the vitest JSON result (best-effort).
let parsed = null;
try { parsed = JSON.parse(readFileSync(JSON_OUT, 'utf8')); } catch { /* crash/no file */ }

const files = [];
const failures = [];
let total = 0;
let passed = 0;
let failed = 0;

if (parsed && Array.isArray(parsed.testResults)) {
  for (const f of parsed.testResults) {
    const fileName = (f.name || '').replace(`${ROOT}/`, '');
    let fp = 0;
    let ff = 0;
    for (const a of f.assertionResults || []) {
      total++;
      if (a.status === 'passed') { passed++; fp++; }
      else if (a.status === 'failed') { failed++; ff++; failures.push(`${fileName} › ${a.fullName || a.title}`); }
    }
    files.push({ file: fileName, passed: fp, failed: ff });
  }
} else if (parsed) {
  total = parsed.numTotalTests ?? 0;
  passed = parsed.numPassedTests ?? 0;
  failed = parsed.numFailedTests ?? 0;
}

// Fold in the scorecard metrics (written by scorecard.test.js during the run).
let scorecard = null;
try {
  const s = JSON.parse(readFileSync(SCORECARD, 'utf8'));
  scorecard = { precision: s.precision, recall: s.recall, leakRate: s.leakRate, cases: s.cases };
} catch { /* scorecard not produced (e.g. ollama absent → suite skipped) */ }

const record = {
  ts: new Date().toISOString(),
  commit: process.env.GITHUB_SHA || process.env.SIGIL_COMMIT || gitShaShort(),
  success: exitCode === 0,
  total, passed, failed,
  durationMs,
  scorecard,
  files,
  failures,
};

appendFileSync(RUNS_LOG, `${JSON.stringify(record)}\n`);
regenerateMarkdown();

// Surface the log location and exit with vitest's code (preserve the gate).
process.stdout.write(`\n[reliability] logged run → ${RUNS_LOG.replace(`${ROOT}/`, '')} (${passed}/${total} passed${scorecard ? `, leak=${scorecard.leakRate}, p=${scorecard.precision}, r=${scorecard.recall}` : ', scorecard skipped'})\n`);
process.exit(exitCode);

function gitShaShort() {
  try {
    const r = spawnSync('git', ['rev-parse', '--short', 'HEAD'], { cwd: ROOT, encoding: 'utf8' });
    return (r.stdout || '').trim() || 'local';
  } catch { return 'local'; }
}

function regenerateMarkdown() {
  let lines = [];
  try { lines = readFileSync(RUNS_LOG, 'utf8').split('\n').filter(Boolean); } catch { return; }
  const runs = lines.map((l) => { try { return JSON.parse(l); } catch { return null; } }).filter(Boolean);
  const recent = runs.slice(-30).reverse();

  const header = [
    '# Reliability Test Log',
    '',
    'Auto-generated by `npm run test:reliability`. One row per run, newest first.',
    'Metrics come from the scorecard (real Ollama embeddings); `—` means the lane',
    'was skipped (no Ollama). Leak-rate must stay **0**.',
    '',
    '| When (UTC) | Commit | Result | Tests | Leak | Precision | Recall | Dur |',
    '|------------|--------|--------|-------|------|-----------|--------|-----|',
  ];
  const rows = recent.map((r) => {
    const when = r.ts.replace('T', ' ').slice(0, 16);
    const result = r.success ? '✅ pass' : '❌ FAIL';
    const sc = r.scorecard;
    const leak = sc ? String(sc.leakRate) : '—';
    const p = sc ? String(sc.precision) : '—';
    const rec = sc ? String(sc.recall) : '—';
    const dur = `${(r.durationMs / 1000).toFixed(1)}s`;
    return `| ${when} | \`${r.commit}\` | ${result} | ${r.passed}/${r.total} | ${leak} | ${p} | ${rec} | ${dur} |`;
  });
  let body = [...header, ...rows, ''];
  // Append the most recent failures, if any, for quick triage.
  const last = recent[0];
  if (last && last.failures && last.failures.length) {
    body = body.concat(['', '## Latest failures', '', ...last.failures.map((f) => `- ${f}`), '']);
  }
  writeFileSync(MD_LOG, body.join('\n'));
}
