// Fork-bomb backstop (defense-in-depth layer L4).
//
// If this hook is executing INSIDE Sigil's own headless `claude -p` (the daemon
// sets SIGIL_DISABLE_HOOKS=1 on that spawn), exit before doing ANY work — no
// daemon call, no LLM, nothing that could re-enter the loop.
//
// Why here and not only in the shim: the ~/.sigil/bin/sigil-hook shim is
// REGENERATED by `sigil connect`/`init`, and a codegen regression already
// dropped its guard once (2026-07-01 fork-bomb). This lives in the compiled
// hook bundle (dist/hooks/*.js), which is versioned + tested, so it can't be
// silently regenerated away. Imported FIRST in every hook entrypoint so its
// side effect runs before the hook's own imports do any work.
if (process.env.SIGIL_DISABLE_HOOKS) {
  process.exit(0);
}
