/**
 * Stable launcher shims — the fix for baked absolute paths.
 *
 * THE PROBLEM
 * Sigil used to freeze the absolute path of its CLI / hook scripts into the
 * files agent harnesses execute:
 *   - ~/.sigil/CLAUDE.md      → `! /abs/path/dist/cli.js remember ...`
 *   - ~/.claude/settings.json → `node /abs/path/dist/hooks/stop.js`
 * Both break the moment that path moves: an nvm/fnm Node switch relocates the
 * global bin, a reinstall lands in a different prefix, the repo gets moved, or
 * the npx cache rotates. The harness then runs a dead path (MODULE_NOT_FOUND,
 * "command not found"), and memory silently stops working until the user
 * re-runs `sigil init` AND every harness's config is rewritten.
 *
 * THE FIX
 * Write two tiny POSIX shims to a STABLE, version-manager-independent location
 * (~/.sigil/bin/) and reference THOSE everywhere instead of the package path:
 *   - ~/.sigil/bin/sigil       → launches the CLI
 *   - ~/.sigil/bin/sigil-hook  → launches a named hook script
 * The shim path never changes, so harness configs (CLAUDE.md, settings.json)
 * never need rewriting. Each shim records the resolved package dir + Node
 * binary at write time but RE-RESOLVES at runtime when that recording goes
 * stale — so a reinstall self-heals on the next `sigil init` (which rewrites
 * just these two files), and the hook shim fails *safe* (exit 0, no output) if
 * it genuinely can't find its target, rather than erroring into the agent loop.
 */

import { join } from 'node:path';
import { homedir } from 'node:os';
import { existsSync } from 'node:fs';

import { PKG_ROOT, ephemeralPackageRoot } from '../paths.js';

const SIGIL_HOME = join(homedir(), '.sigil');
export const SIGIL_BIN_DIR = join(SIGIL_HOME, 'bin');
export const LAUNCHER_SHIM_PATH = join(SIGIL_BIN_DIR, 'sigil');
export const HOOK_SHIM_PATH = join(SIGIL_BIN_DIR, 'sigil-hook');
// Stable stdio entry for MCP clients (Cursor, Codex, Kiro). MCP configs point
// `command` at this shim instead of `node /abs/dist/server.js`, so the
// registration survives a Node-version switch / reinstall. The daemon also
// serves MCP over HTTP at /mcp for clients that prefer a URL — this shim is the
// universally-supported stdio fallback.
export const MCP_SHIM_PATH = join(SIGIL_BIN_DIR, 'sigil-mcp');

// The directory that holds cli.js and hooks/. Bundled installs use dist/;
// running from source uses src/. Both layouts are `<dir>/cli.js` +
// `<dir>/hooks/<name>.js`, so a single dir covers the shim's needs.
export function resolveDistDir() {
  const dist = join(PKG_ROOT, 'dist');
  if (existsSync(join(dist, 'cli.js'))) return dist;
  return join(PKG_ROOT, 'src');
}

// The Sigil MCP server entry point. Bundled installs use dist/server.js;
// running from source uses src/server.js. Used by MCP-client connectors.
export function resolveServerPath() {
  const distServer = join(PKG_ROOT, 'dist', 'server.js');
  const srcServer = join(PKG_ROOT, 'src', 'server.js');
  return existsSync(distServer) ? distServer : srcServer;
}

// Single-quote a value for safe embedding in a POSIX shell script. Paths with
// spaces (e.g. "/Users/My Name/...") survive; the rare embedded single quote is
// escaped via the standard '\'' dance.
function shQuote(value) {
  return `'${String(value).replace(/'/g, `'\\''`)}'`;
}

function renderLauncher({ dist, node }) {
  return `#!/bin/sh
# Sigil launcher — generated by \`sigil init\`. Do not edit by hand.
# Agent harness configs (CLAUDE.md, hooks) reference this STABLE path instead of
# the package's install path, so a Node version switch (nvm/fnm) or a reinstall
# to a new directory cannot break them. Re-run \`sigil init\` to refresh paths.
SIGIL_DIST=${shQuote(dist)}
SIGIL_NODE=${shQuote(node)}
CLI="$SIGIL_DIST/cli.js"
# Self-heal: if the recorded package path is gone (reinstall / moved repo),
# fall back to whatever \`sigil\` resolves to on PATH — but never to a shim under
# ~/.sigil/bin (that would re-enter this script and fail to parse as JS).
if [ ! -f "$CLI" ]; then
  ALT=$(command -v sigil 2>/dev/null)
  case "$ALT" in
    "") ;;
    */.sigil/bin/*) ;;
    *) CLI="$ALT" ;;
  esac
fi
NODE="$SIGIL_NODE"
[ -x "$NODE" ] || NODE=node
exec "$NODE" "$CLI" "$@"
`;
}

function renderMcpLauncher({ dist, node }) {
  return `#!/bin/sh
# Sigil MCP launcher — generated by \`sigil init\`. Do not edit by hand.
# Stable stdio entry for MCP clients (Cursor, Codex, Kiro): their MCP config
# points \`command\` here instead of at the package path, so a Node-version
# switch (nvm/fnm) or reinstall can't break the registration. Re-pin with
# \`sigil connect\`. (The daemon also serves MCP over HTTP at /mcp.)
SIGIL_DIST=${shQuote(dist)}
SIGIL_NODE=${shQuote(node)}
SERVER="$SIGIL_DIST/server.js"
# Self-heal: if the recorded server path is gone (reinstall), derive it from
# whatever \`sigil\` resolves to on PATH (its dir holds server.js too).
if [ ! -f "$SERVER" ]; then
  ALT=$(command -v sigil 2>/dev/null)
  case "$ALT" in
    ""|*/.sigil/bin/*) ;;
    *) D=$(dirname "$ALT"); [ -f "$D/server.js" ] && SERVER="$D/server.js" ;;
  esac
fi
NODE="$SIGIL_NODE"
[ -x "$NODE" ] || NODE=node
exec "$NODE" "$SERVER" --mcp
`;
}

function renderHookDispatcher({ dist, node }) {
  return `#!/bin/sh
# Sigil hook dispatcher — generated by \`sigil init\`. Do not edit by hand.
# Usage: sigil-hook <name>
#   name = user-prompt-submit | post-tool-use | stop | session-end
# Fails SAFE: if the hook script can't be found (stale install), exits 0 with no
# output so a broken Sigil install never blocks or errors the agent loop.
SIGIL_DIST=${shQuote(dist)}
SIGIL_NODE=${shQuote(node)}
NAME="$1"
[ -n "$NAME" ] || exit 0
shift
SCRIPT="$SIGIL_DIST/hooks/$NAME.js"
[ -f "$SCRIPT" ] || exit 0
NODE="$SIGIL_NODE"
[ -x "$NODE" ] || NODE=node
exec "$NODE" "$SCRIPT" "$@"
`;
}

// Human-readable refusal for an ephemeral (pnpm dlx / npx) install. Shared by
// the shim backstop and the early gates in `sigil init` / `sigil connect`.
export function ephemeralInstallMessage(info) {
  const runner = info.kind === 'npx' ? 'npx' : info.kind === 'temp' ? 'a one-shot runner' : 'pnpm dlx';
  return [
    `Sigil is running from a throwaway ${runner} cache:`,
    `  ${info.root}`,
    '',
    'That directory is temporary — your package manager deletes it, which would',
    "silently break memory, and every agent hook would cold-boot a heavy process",
    'from it (a runaway pileup across sessions).',
    '',
    'Install Sigil with the official installer — it lands on your PATH and',
    'sets up automatically (no npx/pnpx, no separate init step):',
    `  ${info.installHint}`,
  ].join('\n');
}

/**
 * Throw if the running package lives in an ephemeral dlx/npx cache. The single
 * choke point every hook-installing path funnels through (init → connectors →
 * mergeHooks, `sigil connect`, and the GUI's connectConnector all call
 * writeLauncherShim), so this one guard protects them uniformly.
 */
export function assertPersistentInstall() {
  const info = ephemeralPackageRoot();
  if (info.ephemeral) {
    const err = new Error(ephemeralInstallMessage(info));
    err.code = 'EPHEMERAL_INSTALL';
    err.info = info;
    throw err;
  }
}

/**
 * Write (or refresh) both launcher shims to ~/.sigil/bin/. Idempotent: if a
 * shim already exists with identical content it's left untouched (stable mtime,
 * clean dry-run summaries). Returns an array of plan actions for the init
 * orchestrator's summary.
 */
export async function writeLauncherShim({ dryRun = false } = {}) {
  // Never bake an ephemeral dlx/npx path into the shims — it would vanish on the
  // next cache sweep and cold-boots a process per hook fire until then.
  assertPersistentInstall();

  const fs = await import('node:fs/promises');
  const dist = resolveDistDir();
  const node = process.execPath;

  const targets = [
    { path: LAUNCHER_SHIM_PATH, content: renderLauncher({ dist, node }) },
    { path: HOOK_SHIM_PATH, content: renderHookDispatcher({ dist, node }) },
    { path: MCP_SHIM_PATH, content: renderMcpLauncher({ dist, node }) },
  ];

  const actions = [];
  if (!dryRun) await fs.mkdir(SIGIL_BIN_DIR, { recursive: true });

  for (const { path, content } of targets) {
    let existing = null;
    try { existing = await fs.readFile(path, 'utf8'); } catch { /* absent */ }

    if (existing === content) {
      actions.push({ action: 'skip', path, detail: 'shim up to date' });
      continue;
    }

    const action = existing == null ? 'create' : 'modify';
    if (!dryRun) {
      await fs.writeFile(path, content, 'utf8');
      await fs.chmod(path, 0o755);
    }
    actions.push({ action, path, detail: existing == null ? 'stable launcher shim' : 'refreshed (paths re-pinned)' });
  }

  return { actions };
}
